name: docker-ci

on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  # enables manual trigger
  workflow_dispatch:

env:
  DOCKER_REPOSITORY: mentatis
  DOCKER_IMAGE_NAME: gulp-core
  PYTHON_VERSION: 3.13

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    # makes sure it doesn't finish the minutes quota if stalls
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Get Docker tag (git version)
        id: get-docker-tag        
        run: |
          GIT_DESCRIBE=$(git describe --tags --always)
          echo "git_version=${GIT_DESCRIBE}" >> ${GITHUB_OUTPUT}
              
      - name: Output Docker tag
        run: echo ${{ steps.get-docker-tag.outputs.git_version }}
      
        # docker buildx build --progress=plain 
        # --build-arg _PYTHON_VERSION=$PYTHON_VERSION 
        # --build-arg _VERSION=$(git describe --tags --always) 
        # --build-arg _MUTY_VERSION=$(cd muty-python && git describe --tags --always && cd ..) --rm -t gulp-core .
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      - name: Get muty_versions
        id: vars
        run: |
          echo "version=$(git describe --tags --always)" >> $GITHUB_OUTPUT
          echo "muty_version=$(cd muty-python && git describe --tags --always)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          no-cache: true
          progress: plain
          build-args: |
            _PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            _VERSION=${{ steps.vars.outputs.version }}
            _MUTY_VERSION=${{ steps.vars.outputs.muty_version }}
          tags: |
            ${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.vars.outputs.version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push [${{ env.DOCKER_IMAGE_NAME }}]      
        uses: docker/build-push-action@v6
        with:
          context: .
          no-cache: true
          build-args: |
            _VERSION=${{ steps.get-docker-tag.outputs.git_version }}

          # if false it will only build
          push: true
          tags: |
            ${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.get-docker-tag.outputs.git_version }}
