name: docker-ci

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  # enables manual trigger
  workflow_dispatch:

env:
  DOCKER_REPOSITORY: mentatis
  DOCKER_IMAGE_NAME: gulp-core

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    # makes sure it doesn't finish the minutes quota if stalls
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Docker tag (git version)
        id: get-docker-tag        
        run: |
          GIT_DESCRIBE=$(git describe --tags --always)
          echo "git_version=${GIT_DESCRIBE}" >> ${GITHUB_OUTPUT}
              
      - name: Output Docker tag
        run: echo ${{ steps.get-docker-tag.outputs.git_version }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push [${{ env.DOCKER_IMAGE_NAME }}]      
        uses: docker/build-push-action@v6
        with:
          context: .
          
          build-args: |
            _VERSION=${{ steps.get-docker-tag.outputs.git_version }}

          # if false it will only build
          push: true
          tags: |
            ${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.get-docker-tag.outputs.git_version }}
